# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: covid19-line-noti-lambda
frameworkVersion: '2'
useDotenv: true
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stackName: covid19-line-noti-lambda-stack-${env:STAGE}
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE}
  region: ap-southeast-1
  environment:
    COVID19_API: ${env:COVID19_API}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - S3:*
            - ec2:*
            - lambda:*
            - kms:GenerateDataKey
            - kms:Encrypt
            - kms:Decrypt
          Resource: "*"

functions:
  covid19-line-notification:
    handler: action/covid19-handler.covid19TodayCaseNotification
    name: covid19-line-notification-${env:STAGE}
    description: 'Job time 10:30AM : covid19 push line-notification'
    memorySize: 4096
    timeout: 900
    disableLogs: false
    tags:
      Name: covid19-line-notification
      Project: Covid19Lambda
      Environment: ${env:ENVIROMENT}
    events:
      - schedule:
          rate: cron(30 03 * * ? *) #GMT +7.00
  thai-covid19-line-notification:
    handler: action/covid19-handler.covid19SongkhlaTodayCaseNotification
    name: thai-covid19-line-notification-${env:STAGE}
    description: 'Job time 10:30AM : covid19 push line-notification'
    memorySize: 4096
    timeout: 900
    disableLogs: false
    tags:
      Name: thai-covid19-line-notification
      Project: Covid19Lambda
      Environment: ${env:ENVIROMENT}
    events:
      - schedule:
          rate: cron(31 03 * * ? *) #GMT +7.00
  lottery-lated-notification:
    handler: action/lottery-handler.lotteryTodayCaseNotification
    name: lottery-lated-notification-${env:STAGE}
    description: 'Job time 16:00PM : lottery push line-notification'
    memorySize: 4096
    timeout: 900
    disableLogs: false
    tags:
      Name: lottery-lated-notification
      Project: Covid19Lambda
      Environment: ${env:ENVIROMENT}
    events:
      - schedule:
          rate: cron(00 09 * * ? *) #GMT +7.00
  sawaddee-today-notification:
    handler: action/sawaddee-handler.sawaddeeTodayNotification
    name: sawaddee-today-notification-${env:STAGE}
    description: 'Job time 8:00AM : sawaddee push images line-notification'
    memorySize: 4096
    timeout: 900
    disableLogs: false
    tags:
      Name: sawaddee-today-notification
      Project: Covid19Lambda
      Environment: ${env:ENVIROMENT}
    events:
      - schedule:
          rate: cron(00 01 * * ? *) #GMT +7.00
  check-eth-btc-notification:
    handler: action/crypto-currency-handler.CryptoCurrencyNotification
    name: check-eth-btc-notification-${env:STAGE}
    description: 'Job time At every 5th minute. : check btc and eth line-notification'
    memorySize: 4096
    timeout: 900
    disableLogs: false
    tags:
      Name: check-eth-btc-notification
      Project: Covid19Lambda
      Environment: ${env:ENVIROMENT}
    events:
      - schedule:
          rate: cron(5 0 * * ? *) #GMT +7.00
  check-cws-today-notification:
    handler: action/crypto-currency-handler.CryptoCurrencyTodayNotification
    name: check-cws-today-notification-${env:STAGE}
    description: 'Job time : check crypto currency line-notification'
    memorySize: 4096
    timeout: 900
    disableLogs: false
    tags:
      Name: check-cws-today-notification
      Project: Covid19Lambda
      Environment: ${env:ENVIROMENT}
    events:
      - schedule:
          rate: cron(0 2 * * ? *) #GMT +7.00
      - schedule:
          rate: cron(0 5 * * ? *) #GMT +7.00
      - schedule:
          rate: cron(0 12 * * ? *) #GMT +7.00
      - schedule:
          rate: cron(0 16 * * ? *) #GMT +7.00
  view-facebook-pages:
    handler: action/facebook-page-handler.callFacebookPage
    name: view-facebook-pages-${env:STAGE}
    description: 'Job time At every 5th minute. : view-facebook-pages'
    memorySize: 4096
    timeout: 900
    disableLogs: false
    tags:
      Name: view-facebook-pages
      Project: Covid19Lambda
      Environment: ${env:ENVIROMENT}
    events:
      - schedule:
          rate: cron(5 0 * * ? *) #GMT +7.00

