# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nexter Pay Lambda CI

on:
  push:
    branches:
      - develop
      - test
      - uat
      - master
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: variable-mapper
        uses: kanga333/variable-mapper@v0.2.0
        with:
          key: "${{ steps.extract_branch.outputs.branch }}"
          map: |
            {
              "master": {
                "environment": "production"
              },
              ".*": {
                "environment": "development"
              }
            }
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install Plugin dotenv
        run: npm install -g serverless-dotenv-plugin
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.5w6/CstcHJfQgDQ1eqfvwLWybZqjm4g9UpXyhies }}
      - name: Create env file
        run: |
          cp .env.${{ env.environment }} .env
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy Lambda functions
        run: sls deploy -s ${{ env.environment }}
